#+TITLE: D1-海南旅行日记-抵达海口
#+TAGS: date/2025-12-04 日记 旅行 海口 D1

* 海南旅行日记-抵达海口
凌晨四点左右的时候，满怀着DokiDoki期待的心情，我终于亲眼目睹了火车登上通往海口的轮渡，说来也奇妙，感觉所谓火车登上轮渡，不过是从一片陆地移动到另一片陆地罢了。

经过了漫长的2小时休息和等待，火车最终在海口站停靠了，出站第一件事就是取车。不过当我到达取车点的时候，发现了一个糟糕的情况，我要取的车被一辆大货车拦住了，不过好在那辆大货车的快递员马上就过来了，于是我和他商谈，他终于把车开走了，于是我就这样开着租来的车开启了旅途。

当然一开始租这个车的时候我没料到是混动，以为是纯电，不过现在要换也来不及了，只能先用着，但我仔细想觉得混动也很强，因为混动可以大幅度降低电油耗能，优化能源效率，所以总成本不会比原来预计的高多少，大概吧。

首先第一件事就是去看海滩，于是我把车开到了金沙滩滨海公园看了看，一眼就被那真正的沙滩震撼到了，如此干净的蓝天，如此一望无垠的沙滩啊~

不过因为我要先去看火山，为了赶时间我只是看了一眼，拍了几张照片就离开了金沙滩滨海公园，之后我则是开车路过许多窄路和弯弯曲曲的村镇路况，来到了一个村庄停车场，在这附近，吃上了美味的海南粉，这是来海南的第一次早餐。

海南粉的口感是黏黏腻腻的，其实还挺带感。

吃饱了之后，我来到了雷琼世界地质公园，这里是海南的一座死火山的所在地，这座火山被热带雨林包裹着，直到进去后我才发现这点，于是我开始有点后悔没戴上防蚊的露水了，因此我登上火山后也被蚊虫叮咬，腿部几处瘙痒。

不过这座火山，因为火山灰熔岩沉积，土壤是真的肥沃，整片火山都被绿色植物所覆盖，有一种绿色火山废墟的美学，毕竟这是个死火山。

而如果你深入火山底部，你会看到一个火山洞穴，也许地下的熔岩曾经就是从这个洞穴里喷发出来的吧。

在这个公园，我也看了许多科普的东西，原来地址公园和海边那种黑色的带孔洞的石头，就是叫做火山岩，而这个火山公园的道路都是火山岩铺设的，据说火山岩是熔岩冷却后的产物，海南也许曾经就是一个火山活动非常活跃的地区，所以沉积着许多的熔岩石。

安山岩和玄武岩也都是熔岩冷却后的一种熔岩石，各种不同种类千奇百怪的熔岩石也非常多呢。

下午比较不幸的是在窄路行车的适合，又因为没主意边距撞到了别人的汽车，于是我报了保险，并请交警来处理，交警表示要等我能联系上车主才能处理，于是我就继续旅行。

下午的第一站是一个小海滩，在海滩上张开双臂，感受海风吹拂的感觉可太舒服了，不过因为后面还要别的要看的，所以我没有久留。

第二站是五源河湿地公园，我将车停在了一个地下停车场，然后前往那片湿地河流，那是一片汇入大海的河流，我沿着沿岸各类热带植物的河流行走，终于来到了入海口，也许河流在入海口因为冲积泥沙的缘故，入海口确实形成了一个小小的三角洲，我对这一个发现兴奋不已，依然吹拂着海风散步回程。

下一站是观海台，不过到了观海台我才发现，其实假日海滩和观海台仅相差一公里，于是我干脆到假日海滩停车去了。

接下来的重头戏，就是脱掉鞋子在海边的沙滩上行走，我感受着海风的吹拂，在海边沙滩上散步，海水不断冲洗着我的脚，亲自感受来自海水的感觉，那是一种非常舒服和轻盈的感觉，看着汹涌的海面和海浪不断往上冲击、拍打，我也感受到了一种非常奇妙的感觉，真是不可思议呢。

在海边，海风的吹拂下终究会玩累，散步了一圈，我洗了洗自己的脚，然后就前往旅馆了。

前往旅馆的途中，真是被窄路复杂的路况和窄路停车折磨了一遍，不过好在这一次磨练，我尝试了多次终于停好车了，感觉开车最难的一件事情就是停车了（X）。

在旅店办好手续后，我来到了友谊阳光城探索神秘的二次元商铺，一开始在下层看到的只是平平无奇的商品，不过随着往上层走，我渐渐地发现，这个商铺真的到处都是二次元的商品，琳琅满目的各种手办和周边，几乎什么东西都应有尽有。

在游览的过程中，我还发现了一个非常奇妙的商场内美食街，这个街道每隔一段距离都设有吃饭的座位，而边缘则是各式各样的饭店，游览一圈这些饭店，你会发现来自中国各地的特产都在这里。

有时我也感觉，我是不是到了日本，因为在海南旅游，一样能购买盲盒，体验开盲盒的乐趣。

也许正是有今天的经历，我才理解了手办收集者和开盲盒的人的乐趣吧。

其实我只是一时兴起买了一个自己喜欢的芙莉莲的盲盒，结果没想到一开出来就是隐藏版的徽章，正好命中自己最喜欢的角色。这一刻我突然感觉自己是不是欧皇附体了。也许这种兴奋和乐趣就是开盲盒的乐趣所在吧。

吃饱了饭后，我在商场逛了多个地方，看了各种各样的东西，果然这里也有舞萌的街机，非常的有意思。

一切都满足后，最后我来到了旅店附近的猫咖馆，在这里撸猫好好放松了一下，猫猫非常地可爱。就是有一只猫咪有一点点凶凶的样子，会对你使用猫猫拳。

今天真是充实的一天呢，希望明天也能这么愉快。
