#+hugo_base_dir: ~/yumieko/
#+hugo_section: others/end-years-tecture
#+export_file_name: index.md
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: toc true
#+filetags: 2025 年终总结 琪可 
#+TITLE: 2025年终总结

* 前言
又一年过去了呢，为了保持定期反思和写记录的习惯，我得好好复盘复盘这一年学到的东西。

* 做了什么
关于我这一年里做了什么，其实年初做的事情我也记不太清楚了，不过今年做的大概的事情列在下面吧：

- 更新和配置操作系统与软件工作流。
- 尝试和折腾新的软件使用。
- 学习新的编程语言和程序哲学。
- 反思人生。
- 搬家。
- 立了几个不切实际的程序项目，做了一段时间后弃坑。
- 更新思维方式（即大脑的OS）。
- 使用RPG Maker及Godot开发游戏。
- 游戏项目迭代了10多次，依然没能完成迭代。
- 反复咀嚼和反思个人理念、政治社会等思考。
- 为Godot开发工具和库。
- 搭建个人NAS服务，搭建博客网站。
- 接触并搭建misskey，matrix。
- 画了几幅新的画。
- 造了几十个新的词，造了几个新的字。
- 个人世界观完善。
- 爱上了Emacs、Guix和Lisp，并疯狂折腾Emacs、Guix和Lisp。
- 折腾Guix，并在自己的guix频道写了大量服务的实现。
- 参加Gamjam。
- 海南旅游。

ummm，不得不说，把大概的事情列出来，其实一年下来也做了很多的事情了嘛，虽然我总感觉我几乎什么都没做，总是在无所事事地度过人生。

* 迭代的一年
迭代的一年，我大概这么评价今年的这一年的生活吧，感觉今年是尝试新的东西最积极，思维最踊跃的一年了。

** 知识管理的迭代
难以想象的是，短短一年多的时间，我的知识管理软件完成了从 Obsidian -> OrgMode -> EKG 的转变。

笔记软件的更换，也许也象征着我思维方式的迭代，以前我习惯用Obsidian文件夹式层级整理思维。

然后发现还是双向链接式整理更酷，于是花了点功夫将知识体系拆分成一个个节点并整理成了OrgMode图谱。

后来找Emacs兼容AI方案的时候意外发现了EKG，这是一个完全不依赖双向链接，而是纯靠标签和数据库整理的插件。

这个插件，把我的思维拉回到了最本质的快速查快速记的需求，因为这个插件还兼容AI，所以只需接入AI就能获得一套AI驱动的速查知识库，完美！

好吧也有不完美的地方，一方面是这玩意用低本AI实在别扭，另一方面是这玩意还比较实验性，AI方面bug挺多，而且这玩意因为用的sqlite数据库，也没办法用syncthing同步，毕竟syncthing最怕数据库这种频繁修改且没法增量的二进制文件。

所以我还在想办法弄个更好用的知识管理软件。

** 操作系统的迭代
谁能想象，短短的一年内，我给我的操作系统也迭代了两次。
最开始是想换个不容易滚挂的操作系统，于是从Archlinx迁移到了Gentoo。
本以为Gentoo已经够折腾了，没想到折腾好Gentoo后仅过了几个月，就了解到了更强大的操作系统 —— Guix。
就这么说把，Guix简直是将Archlinux、Nix、Gentoo和Debain的优点全都集成于一体了，硬要说有什么缺点，我只能说生态差就是唯一的缺点了。
Gentoo虽然因为保守的更新策略，比Archlinux更稳定，但要让用户花很多时间构建，Guix通过哈希比对，服务器直接分发计算出的构建结果，效果几乎和直接裸机构建差不太多了。

** 游戏的迭代
在这一年之内，游戏也迭代了许多次，也许迭代的不只是游戏，随之迭代的还有游戏的开发和思维方式。

原本我总是执拗着坚持着想要继续做出项目，但是渐渐地总感觉自己对游戏方面付出的努力是假性的，并没有触及到真正难的玩法迭代。

以前开发游戏总是容易犯做过多纸上功夫的错误，现在的话，则是因为迭代到最后，失去了方向，连自己也不知道该怎样迭代才是正确的路了，照顾不好自己的精神需求导致反复的程序内耗和游戏倦怠，游戏开发进度也在无数次的内耗中拖延和消磨。

这一年将近尾声，我终于领悟到了一点，也许其实根本不用这么麻烦吧，不用苛求制作出心目中完美的游戏，既然迭代许多次，也很难触及到问题的根本。

那么不如学会把思路逆转过来，想想看自己到底最想做什么样的游戏，再朝着自己想做的游戏的方向去改进。

也许这一年来游戏思路的卡壳，其实是因为我的思维大概一直都在围绕着一个点打转，不断想着要做一个基于状态的恶作剧游戏，却又忽视了这个基于状态的恶作剧游戏没法完成的根本原因 —— 单次测试和迭代要付出太大的开发成本。

总是想要制作各种有趣炫酷的技能和机制，却没办法做出来，也许是因为我忽视了这些新东西引入的隐性成本，那就是玩法的迭代成本吧。引入一个新的动词和游戏内动作，就等同于引入了一个全新的玩法。

这一年我和朋友不断围绕着开发方向争吵，我总是强调可扩展性，给游戏内的角色动作和能力定位太过抽象空泛，生怕写得太具象会导致游戏失去可扩展性，我就不能灵活地给游戏定制一套炫酷的BOSS战了。

但实际是，过于抽象和空泛的东西反而无法让游戏完成，也无法准确验证玩法和机制。

我总是痴迷地执着于只要积累经验，付出时间就能成功的幻象，也许正是被这层幻想所困，我才无法完成我的游戏项目吧。

讽刺的是，GameJam项目不知是因为赶时间的缘故还是没有认真迭代玩法的缘故，总是能奇迹般地完成，虽然我也知道做得并不是非常好玩。

** 思维方式的迭代
也许这一年，看似平淡无奇，实际上，一场轰轰烈烈的关于思维方式的革命正在悄然展开。
表面上这一年我只是将工作流和社交媒体来了一次大的切换和更新，实际上，错了……
这一年，我打破了高度依赖的旧的思维定势，接受了一套新的精神和思考方式。
隐私和自由方面，我渐渐接受了自由软件的精神，开始追求更好的隐私，尽可能减少牺牲隐私换取便利的情况，现在我也终于理解了何为自由软件的自由，那是不受制于任何大企业垄断，独立分发软件的一套理想的平行体系。
代码、工作流和项目组织管理思维方面，也掀起了一场新的浪潮。

效率与学习方面，这段时间我确实随着学习Lisp，也接触了不少架构思想，现在我意识到，易于学习所带来的效率，确实比使用鼓励懒惰思维的软件更高效。
就像是AI的使用一样，将一切全部交给AI，放弃独立思考固然方便，但无法从AI真正学到有价值的东西，也无法让AI做出足够好的东西。
要真正学到这些东西，还是得亲自查阅多方资料交叉验证，以及了解你做的东西背后的原理和逻辑，这对于编曲、绘画等创作领域同样重要。
固然软件像VSCode等，能比Emacs这类软件带来更多的便利性，但它牺牲的是自由使用、自由修改的权利，鼓励的是思维方式的惰性，长期养成思维方式的惰性，反而会渐渐变得不愿意思考更好的工作流改善思路。
自从用上了Emacs后，时刻伴随我的就是新的改善工作流的思路和许多新的发现，

* 重复的一年
整整一年，回想起这一年，我的感觉就是，不断地重复着许多同样的类似的事。

一遍遍重复着同样的代码操作却因为思维的惰性，完全不懂得摸索能让操作变得更轻松、更便捷的方法。

直到最后几天，可能是经过一段时间的旅行，大脑放松下来后，才突然意识到，其实很多重复的操作，明明不需要这么猛地反复进行，而是完全可以自动化的。

整整一年，感觉大部分的时间都宅在家里忙忙碌碌，直到最后两个月才意识到这样下去不行，最终决定出去旅行看看，于是在海南环岛旅行玩了一圈。

说来也奇妙，海南旅行时的那种出去玩的心态，和现在的这种无所事事的心态，感觉压根就不是同一种心态。

感觉海南旅行的日记也许也可以考虑整理整理发出来吧。

* 程序方面的进展
今年在程序方面，仔细回想，我也做了挺多事了。

首先是Guix频道方面，我凭一己之力，竟然用docker包装了超多的服务，这都是为了给我的这台NAS找后端程序所做的尝试，其中有很大一部分试了试最后因为软件本身不满意所以还是放弃了。

项目方面，除了游戏本身的项目外，我做了这些项目：
- LiquidNeko: 本来打算做成一个操作系统的，不过最后在跟着教程写完一个lisp解释器后，才发现因为这个项目太不切实际，感觉做下去浪费时间最后放弃了。
- NightCat Srpg：算是折旧的夜之城传说初代原型，当时是用godot写的通用SRPG系统，我把它开源了。
- NekoWrighter：用gdscript配合godot-s7写的godot插件，可以类似 (玩家 对话 "你好") 的格式来定制玩家的各个行动和剧本的插件，是做到基本可以用的程度了，可惜最后也没实际用上。
- Ngrs：Guile与Rust的绑定程序，这是年底做的，为了方便Bevy和Guile绑定的程序。

运维方面的话，最大的成就大概就是搭建了misskey和matrix两套服务吧，而且还给服务器搭建了很多其它的服务，自己的nas也搭了不少有意思的服务，仔细想想，虽然感觉做的事情挺多的，但折算下来完成的事情好像也就那么点屈指可数。

* 创作方面
** 画画
今年依然是画画比较少的一年，好像我平时画画都很少，总是要拖几个月才憋出来一副新画的节奏，但奇妙的是，我画画水平好像一直都很稳，稳在了一个当前的阶梯，很久没画似乎也不会下滑太多。

大概是因为手感差不多，画画的认知也没有特别大的变动吧，个人感觉也许画画实质上是认知优于手感的艺术，只有找多了参考才能画得好。

我也并不是特别擅长找参考啥的，所以也就只能画出像儿童画一般的低水平光影风格。

今年新画的，基本只有四幅，主要集中在年底，在出于纯粹的灵感画完《ChikoChiko》这张后，陆续画了《美少女小梦的休憩》、《星夜巡礼》、《月夜下的夜莺行动》三幅画。

** 造语
造语的进度一直很缓慢，可能是因为造语项目并不是特别主要的项目，而且现阶段也没有一个用得特别顺手的造语工具，哪怕是词库管理这类也基本找不到。

所以即便是现在，我的香格里拉文依然没能造完基础的200个斯氏核心词，更别说比较进阶的词组了，不过关于香格里拉词的灵感倒是一直都有，之后还得一个个给这些香格里拉文造字呢，造语真是个很繁重的工作。

未来我也想开发个自己的造语工具，也许那样的话，造语进度就会流畅许多吧（大概）。

* 联邦宇宙
认识到联邦宇宙，大概是这一年来最不可思议的成就之一了。联邦宇宙（fediverse）是一套分布式的社交网络，在这套网络体系中，人人都可以自建实例，所有实例节点相互都能互联，通过这套实例组成一套庞大的网络体系，每个人都能自由选择实例，也能获得自己的主导权，完全自建实例也可以将数据由自己托管，避免对大平台和垄断的依赖。

此外联邦宇宙因为现阶段圈子少，而且有一定门槛，所以各类抽象言论也比较少，虽然以后随着圈子增大可能会增加。不过没关系，自建实例都可以屏蔽杂音和自管理，其它实例的用户也能通过迁移接口将帐号迁移到别的实例。

在联邦宇宙上，认识的形形色色的人，因为联邦宇宙本身的原理是主动订阅制的，所以也基本不会产生特别算法洪流的感觉，就是中文实例上确实很多人也还是有点喜欢讲各种听不懂的黑话。

* 明年要做的事
明年的话，首先，我希望能尽量完成《夜之城传说》这个项目，还有随性做的小项目《远航计划》。

然后，我也想要适当地增加画画的比例和数量。

造语方面，希望尽可能完成斯氏核心词吧。

程序方面，我希望尽量完成 Bevy_Scheme 这个项目，然后再尽量完成我想做的两个项目的核心并持续更新项目，分别是：

- nnw：一个多模态、高度松耦合、高度灵活性和可定制性、可选多后端、可选联网同步服务、matrix支持和方便远程协作的万能知识管理软件兼文本引擎。
- fujiko：一个绘画/白板 界的 emacs软件，从最基础的“画笔” 和 “画纸” 两个概念开始，在无限大的 “画纸” 或者说白板上绘画任何可绘制东西（包括但不限于插画、漫画、思维导图、图谱、字体、矢量图、画笔、图章、交互、游戏地图、GUI）的软件。

* 总结
感觉也没什么好说的了
