#+hugo_base_dir: ~/yumieko/
#+hugo_section: others/chikochiko_dokidoki
#+export_file_name: index.md
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: toc true
#+filetags: 琪可 明琪 小梦 心动 恋爱
#+TITLE: 琪可琪可的心动史

* 前言
大家好，这里是明琪琪可，我是一个内向又敏感，容易心动和胡思乱想的男孩子。

近期的经历和反思，让我意识到，总是闷在家里，不出门参加线下的社交活动，难免会感觉到寂寞，进入浑身没有精力的状态，也会变得不擅长与人打交道，以及容易胡思乱想。

说来也奇妙，内向的人虽然独处都很开心，但是如果长时间被动独处，又难免会感到孤独。

结合近期的经历，我想在这里谈谈个人的恋爱观和心动史。

之所以叫心动史，是因为琪可是容易胡思乱想的类型，容易感到心动，所以我想试着记录下曾经让我感觉到心动的各种回忆，哪怕我从来没有过真正意义上的恋爱感情，都是大多数情况都是单方面自认为的恋爱，不过对我而言，每一次心动都是与奇妙的缘分相遇，值得记录的美好回忆，哪怕曾经有过各种不愉快。

* 最早的感情经历
最早的一次感情经历，大概是初中时期，刚加入MLP圈子的那时候吧，那时我进入的圈子里大多数都是一群初高中的MLP动漫爱好者。我那时我在网上认识了一个处CP的女生，当时都很喜欢萍琪这个角色，所以我们有很多共同话题，关系也挺不错，经常在网络各个群聊一起玩耍的。

不过那时候我并不懂事，也根本不懂得恋爱是啥，因为她表示喜欢我，所以我们两个就试着组了QQ情侣空间。但是可惜随着时间的推移，我即便发现并不喜欢她，依然还是自我欺骗，而且那时我还太小，看到对方的空间总是消极信息，也不知该如何安慰，说了很多废话。

之后又因为她退出了圈子，也不再是MLP的头像，换成了大概第五人格的头像把，我感觉到了背叛，因为那时我的观念大概就是只有MLP是最好的作品，退圈就等同于背叛。所以渐渐地也感觉到物是人非，不怎么喜欢她。

恰好这个时候又认识了另一个女孩子，真的网名还是不方便吐露，就叫她莉莉吧。是同城的，成绩非常优秀，性格也非常开朗，于是对这莉莉心生憧憬。

当时我很笨蛋地，竟然还对原来的那个女生说了不确定是不是喜欢莉莉的烦恼。当时她还查了下打趣地说莉莉是展会上女装的，后来我问了莉莉本人才知道，因为莉莉当时在展会上穿得很好看，被很多人认为是女装大佬，其实是真正的女孩子。

后来也因为我和她关系逐渐熟络，那个孩子大概也看不下去了吧，主动对我提出分手，说是要放我自由。当时我怎么想的也记不清了，从现在的我视角来看，我总是感觉那时候的我很冷漠，很低情商，虽然是伤心了一会儿，但是对那种事情竟然还冷处理了。

这也难怪，大概因为我就是这样笨蛋和执迷不悟的人吧，之后也再也没有遇见过喜欢我的异性了。

就算现在的我看来，那时的我也真的是太过分、太冷漠、太偏执了，一味地执迷于相信自己认为的正确，不愿意理解他人。

同性的朋友倒是有一个，现在和我关系也是非常亲密，可以类比女孩子的闺蜜一样的情感，不过那是后面讲的了。

* 与莉莉的相处
前面提到过，我和初次感情的那个女孩子分手后，和莉莉的相处也随着时间推移熟识起来。这段时间的相处，大概是从初二到高一的阶段吧。

虽然是很短暂的时间，但是因为经常线下见面一起玩的缘故，我玩得很开心。

高一那时候因为抑郁症住院期间，莉莉也经常跟我去玩，还会跟我抱抱。

确实，两个人相处的幸福时间总是很愉快的，但一直都是友情的愉快，然而我们的友情，却在后面因为意见分歧而破裂了。

事情的起因要从我在圈子的经历说起。

那时我也是比较爱出风头，爱引起关注的，所以经常在圈子主群用可爱的语气开玩笑说话之类的，说白了就是在正常聊天的群玩语C。

后来我还加入了Brony社区和文社之类的组织，也开始对圈子的现状进行反思，但我也希望能改变这个圈子的现状，于是在Brony社区开始行动，用类似传销之类的话说来拉人，被群里的人暴躁地批评了。

后来我看见莉莉也参与了商业化氛围严重的约稿等活动，还跟我说要不要越商稿之类的，于是我也逐渐感到反感和失望。

因为那时的我，并不在意商业化什么的，我只关心为什么大家都不能好好地一起认真谈论作品，为什么不能一起玩耍，为什么总是要为着几个约稿和几笔钱争来争去。

后来我也听圈子里的前辈说，以前的圈子不是这样的，在以前很多在别的圈子越商稿的创作者，在这个圈子都是免费作画，因为那时候圈子普遍有个共识，就是出于热爱的同人创作和给朋友的作品不应该收费。

所以这时冲突已经埋下了种子，后来因为我一次频繁的语C行动最终惹恼了莉莉，她将我挂在墙上的行为，又触碰到了我对不许网络暴力这一基本底线，所以我们两个的友情就这样破裂了。

从那之后，我用很长的时间调整和恢复，最终学会了专心参与创作。

* 夏日的彩虹
对我来说，最甜蜜的一段友情，大概是在一个暑假期间。

那时我和父母看了一个教育宣传会，最终决定参与一个记忆训练的集训营，于是这段暑假期间就进入了集训营，准备进入为期两周左右的记忆力集训。

而就在这个地方，我和两位比较纯粹的异性朋友相遇了。我不知道是什么时候了，反正我和其中一位非常聊得来，就叫她夏虹吧，夏虹愿意倾听我谈论MLP的各种故事，我也愿意和她分享自己的故事。

因为害怕受伤，所以那段时间我早就给自己筑起了心墙，但只有那个暑假是我中学时期唯一敞开心门的一段时间。

不过当时的我也只想到友情这一层面，根本没有恋爱相关的想法。

在这段时期，过得非常愉快，我和她总是牵着手到处走，看各种有趣的东西，欣赏各种不可思议的东西。

那时我记得同集训营还有女孩子不知道什么原因哭泣，于是我跑去问老师该如何安慰人，老师对我也印象挺好。

另一位异性朋友并不是那么聊得来，但也经常看到，是个假小子的酷酷形象，和夏虹应该是很好的朋友，所以也总是给我深刻的印象。

那段时间过得非常快乐，我还第一次看到了彩虹，那是非常浪漫的彩虹。那时候还有一个生日活动，同学们都在庆祝在这段时间过生日的同学的生日，我记得生日吃蛋糕用的叉子，那时都被我当作珍贵的回忆保存下来了。

但是很快，就到了分别的时候，我们因为快要分别了，感到伤心，她送了我一本笔记本，而我们两个在临走前给了彼此一个抱抱。

这一直都是我心目中最珍贵，最美好的一段回忆，因为之后在现实中再也没有过类似的回忆了。

顺便说一下我和她的后续，大概在后续之后，还有一次回来复议的听证会，这时候我们都有机会重逢，这是几天后的日子，但是重逢的时候，我想给她欣赏MLP我觉得很棒的音乐，不知道是否有什么误会，对方总给我也戴上自己的耳机刷起各个明星的资讯的印象，从这之后我的内心像是和她隔了一道墙。

那时候的我心中其实真正在乎的只有找到同好这一点，甚至可以说是有些偏执了。

后来也就没有任何联系了，因为我可能根本没有机会和她交换联系方式。

不过我其实依然觉得这份回忆很宝贵，很想珍藏，于是我将那本笔记本藏在了家里一个很重要的地方，希望好好珍藏起来。可惜，后面想找出来的时候，发现在再也找不到了，童年的回忆就这么消失了。

而且后来还因为家里人的一次过错，一把火将家里的很多东西都烧掉了，这算是一次浩劫，我的回忆大概也一起被烧掉了吧……

* 与梦暮的友情
后来，在创作者社群中，我认识了梦暮和银星。其实我最初是对银星心生爱慕的，因为我很喜欢他的作品，当时也认为他是浪漫的女孩子。

虽然后来发现是男孩子，而且后来发现那家伙根本就不喜欢人际交往，是个更享受一个人创作的独狼创作者。

所以也就一段时间有过联系，后来就没怎么联系了。

梦暮的话，我是想要试着进入银星的圈子，发现梦暮经常和银星有互动，所以就和梦暮顺便也交了个朋友。

不过我那一次运气也是真的好，逐渐地就和梦暮熟识了，此后无论做什么事都少不了梦暮了，我们两个创造了许多美好的回忆。

从几年前认识梦暮开始，我们一起参与MLP圈子的字幕组的歌词翻译工作，又一起创作各种各样的作品，还一起玩游戏，直到现在，我们依然也是甜甜蜜蜜的好朋友。

值得注意的是，以前有一次我对自认为喜欢的人（后来发现其实其实是误解了）表白，但是对方对我不感兴趣，先是冷处理然后拒绝的时候，那是我心情最难受，情绪波动最大的时候。

那时候，也是多亏了梦暮的陪伴才挺过来，梦暮当时也对我表白了，告诉我他喜欢我，无论有什么事都会陪着我。

也是从那时开始，我们两个人就立下了要做永远的朋友的约定。

毕竟我们两个都是同性的朋友， 而且也都不是同性恋什么的，都知道结婚什么的是不可能的。果然我还是特别特别喜欢女孩子啊~。

当然我也是不止一次幻想过假如我是女孩子的话就好了，不过，我最近也终于意识到应该认同自己身为男孩子的身份了。

因为，比起追求一个心目中的完美自己，还不如认可和接纳真实的自己，比起费尽心思追求改变自己的身体，并为止付出沉重的代价，还不如意识到，是这个世界的体制，是人们的偏见导致了我的痛苦，所以我不仅要作为男孩子，而且要做为一个可爱的男孩子活下去。

希望以后，我和梦暮之间的友情也依然会像现在这样要好。

* 小风的故事
大概是在被莉莉挂人之后那段时间吧，我开始反思和研究圈子里因为某种网络名声不好而销声匿迹的前辈，偶然就发现了MLP圈的内圈层，在内圈层里面的氛围相对来说非常和谐，基本只有谈论作品和分享生活以及个人经历的内容，并没有那么多乱七八糟的争议。

于是我就在这样的圈子里开始成长，那段时间每天的日常就是参与字幕组的创作工作，以及参与群聊讨论之类的，我那时候也是话题很多的，经常谈论各种各样的话题。

那时候里面也有个女孩子，我管她叫小风吧，不过当时我对她没什么意思，就是当作群友经常聊。

小风是很喜欢吐槽的女孩子，她经常在群里吐槽我各种行为。

比如我有一次拿一个人的死讯开玩笑的时候，她说我，“明明是人，却没有一点同理心”，这句话深深刺中了我的内心。

之后随着一些个人经历加深，我多少体会到了许多人的生死安慰，所以我也再也不会轻易地拿别人的生死之类的事情当作梗和玩笑了，而那句话我至今仍然铭记于心，时不时想起来。

除此之外她还吐槽过我的很多事情，也帮过我很多忙，教过我很多人文关怀的道理，可以说在我心目中，一直都算是很不可思议的朋友，虽然总是对我直言不讳，也许我不一定认同她的想法，而且她性格多少有些固执了。

但如果没有这位朋友，我永远都不可能学会如何关心他人、如何爱人、如何跟人打交道等等，一味地停留和执迷于自我无法走出自我。

而且，后来也是因为她的缘故我接触了阿德勒心理学，还看了《爱的艺术》一书，正是她带领我的思维走出了偏执，还让我摆脱了善恶对立的二元框架，以及经验决定性格论的问题。

虽然我并不完全认同阿德勒的观点，我认为人的本质是社会关系的总和，所以人所处的环境和人际关系会是一部分塑造人性格的因素，但最终决定人现在怎么样的，是人自己的目的和主观能动性，比如我们可以主动去结识更多不错的朋友，来确保自己的社会关系相对清净，从而达成自我实现。

之后过了一段时间，因为我在圈子里其它群体的氛围实在受不了了，于是我决心去了解下圈子外面的事情，最终和MLP圈决裂，只留下了之前那个群。

虽然是退圈的那段时间，但也经常和那个群有往来，不过那段时间算是我情绪最不稳定的时期，错把友情、崇拜和期许当作了爱情，对她展开自认为的追求，甚至在520那天对她告白，后来理所当然地被拒绝了。

当时我一冲动就删了她的好友，后来我想加回来，她抛出了那句，“朋友不是你想删就删，想加就加的”。虽然之前也有类似的人说过这样的话，但是第一次有深刻体会也还是那次。

从那之后，我对原来那个群的关系也渐渐淡下来了，虽然后来我和她又重新加回来了，但因为我们圈子不同了，所以沟通也越来越少了。

而那个群，后来群主还因为小风总是太固执把她给踢了，此后那个群就变冷了，再也没有人谈论任何东西了，偶尔我还会在群里发言，但也没什么回应了……

其实，她太固执确实也是个问题，因为总是坚持自己认为的事情，一口咬定一个东西不放。后来她因为创作的痛苦，我也想安慰她，但也被以我不懂为理由给否决了。

不过即便如此，这段回忆还是值得我珍藏的回忆之一。

顺带一提，之后我的个人问题和偏执，也是随着参与了动物朋友社团的活动，渐渐地消失了。多亏了动物朋友社团的朋友，尤其是社长，他们在社群里的分享总是能启迪我的思维，开阔我的视野。

之后我花了很多时间，调和了许多事情，许多原先我带有偏见和潜意识反感的东西，渐渐地也不再那么反感了，现在的我也算是能接受像是约稿、OC之类的词汇了，也学会了如何理解他人的偏执。

至于如何做到这一点，我感觉个人和他人的情绪隔离很重要，就是要意识到，理解他人的情绪，不代表你一定要做什么，也不会改变你自己怎么样。反正自己的观念和信仰是不会变的，跟别人争也没用。

* 小海的故事
其实在我对小风展开热烈追求之前，还有个小插曲，那就是小海的故事。

那是我在未能决定自己的人生方向，开始感到迷茫的时期的一段小插曲。

大概是一直感到寂寞和孤独，渴望从所谓的恋爱获得所谓的慰藉吧，所以那段时间我不断地刷各种恋爱社交软件。偶然间认识了一个女生，我就叫她小海好了。

据我对她的了解，她其实是很传统的那种类型，比较温柔、对动漫比较感兴趣、对生死之类的话题比较讳忌，梦想是去海边旅行看一看海。

不过那时也是和小风差不多时期的，我并不懂得什么是爱，就只是看人家愿意多和我听听歌，我就感觉自己好像喜欢了，心里也好像是有点心动的感觉。当时我告诉她我的烦恼，她表示自己比较慢热之类的。

不过我和她玩得很愉快这点还是没错的，那段时间经常和她相互分享音乐，我听到了许多感觉还不错的音乐，本来可能也不是我感兴趣的题材突然感兴趣了。但动漫的话……咒术回战和少女缘结神都看了，感觉就一般般，没啥感觉XD。

之后我也对她失去兴趣了，就告诉她我没什么感觉了，然后反过来被她调侃我可能是恋爱脑的类型。

其实这两次经历，算是我个人认为对我而言最丢脸的经历了，不过好在后来也终于明白了很多事情，再没出现过类似的情况了。

* 巧克力的故事
之后一次心动的对象，是被称为巧克力的大姐姐，那时她还是大三的姐姐，长期经常维护贴吧和群聊。

她特别喜欢少女终末旅行这部作品，于是我也经常在少终的群里面看见她。

当时我也坦率地和她讲述了自己的恋爱精力，她觉得小时候我的我很可爱。然后我问她关于我现在的物质问题，会有女孩子愿意接受我现在的这种很尴尬的经济状况吗？她表示大概女孩子都希望能有稳定收入来源的人吧。

大概就是她的这句话，让我下定决心不再追求恋爱了，因为我很清楚，经济状况对我而言是硬伤，即便是现在我的经济状况也不容乐观，全靠能理解我的志同道合的伙伴支撑我。

大概的情况就类似星露谷的作者吧，虽然用常人的眼光来看可能认为是黑料，但只有理解过创作者艰难的人才知道创作者的生存处境有多糟糕。

有一个能理解并支持自己理想的人，其实是非常宝贵耶非常幸运的一件事情，毕竟我深切感受到很多人都在孤军奋战。

不过我也理解要求对象经济条件好的女孩子。毕竟我知道，我造成当下创作者生存处境困难的问题，正是体制的问题。

在现有的体制下，任何纯粹的人际关系都被异化成了赤裸裸的金钱交易，无论是男性还是女性，为了求生存都不惜出卖自己的身体健康，通过某种形式的契约将自己的主导权交给他人，正是这种异化的体制导致了现在的绝大多数社会问题。

所以在这样的体制下，还能有星露谷物语的作者和她女朋友那样纯粹的感情支持，其实是非常可贵的事情。

之后那段时间，我还和她聊过很多事情，不过后来也没什么联系了，大概是她继续忙自己的事情去了吧。

* 小玉的故事
大概是在东方project同人展会的时候吧，我看见了一个穿得很可爱的女生。

我对她很在意，于是经常跟着她，但是我又不敢和她搭讪，就总是看着她。

看到她在签名墙上写下了一段签名，于是我拍照表示很感兴趣，就这样我认识了小玉。

一开始我就做了自我介绍，告诉他我是个什么样的人，然后我的现状和参与创作的情况大概如何。她表示自己不会怎样认为，并表示我是个很努力的人。

实际认识和，我发现她确实是很开朗的那种女孩子，和她聊天也挺愉快的，但大概她也有自己的生活吧，经常不在线，加上她是那种外向型的，而这类人大概都有自己的圈子，所以渐渐地我们也没怎么聊到一块了，但我想以后有机会也还是可以再聊几句吧。

* 斑鸠三人组的故事
在和巧克力渐渐地不怎么联系之后，我也暂时只和梦暮相处很长一段时间，这段时间我和梦暮两个人都在一起做游戏，沉浸在创作的乐趣中。

不过过了一两年左右吧，有那么一段时间，情况发生了变化，梦暮因为受到以前圈子的一位朋友跑团的邀请。

于是我们认识了另外两位女性朋友，其中一位非常喜欢魔法少女，我就称她为玲音吧，另一位是则是喜欢比较正经的作品，对LGBT什么的都非常反感的，我叫她卡布奇诺吧，之前那位跑团的朋友给我的印象是非常害羞的猫耳少年，虽然现实其实是个胖胖的男孩子，我就叫他虹茶吧。

开始和这三位相处都相当愉快，也没什么事情，然后我是对他们都抱有某种深交的期待的，想要和他们成为那种能够共同讨论创作，共同看看那片美丽的星空的朋友，所以我经常在群里发一些我希望怎么怎么样的话。

然后我和玲音还有卡布奇诺，这两位我认识他们之后，关系也渐渐熟络起来，当时本来没有什么感觉的，主要就想要当普通的朋友，哪怕有点心动的感觉，但也不能认为是那种心动。

但是虹茶总是说一些要我赶快抓紧追她们之类的话，大概总是觉得我有点心动的感觉吧，虽然内心里是有点心动的感觉，但也不能认为是真的恋爱那种感觉。

所以我就对虹茶谈心，我把我的心动和胡思乱想告诉了他，然后在他的认知里看来，这种感觉就是恋爱。不过恋爱什么的我其实认为不是，但还是受到情绪激动，就相信了虹茶说的话，经常和虹茶吐心思，也很熟络地每天都和两位谈各种话题。

因为那时候我大概是有自己对恋爱的看法的，就是认为感情这些都是要长期的陪伴才会自然而然发展起来的，但是虹茶似乎无法理解我说的这些，总是认为要我抓紧不要错过，害得我受到怂恿而跟着心动，变得着急。

但其实我当时一直都很想珍惜我们之间的友情的，而且我本身也很在乎和虹茶的关系，一直都希望大家只是能一起快快乐乐地玩耍，开开心心的谈论和分享自己喜欢的作品、欣赏作品的感想、创作的心得体会之类的，我理想的友情都是要有深度的交流的，我一直都希望能实现这点。

但很可惜，他们似乎只是浅层圈子的人，我所谓的深度交流，在他们看来就变成了不可理喻和破坏群氛围，搞得群里没有几个正经人了。

虽然我确实也有试图融入他们于是尝试模仿他们的语C行为，结果导致的是我反而给他们留下了更加不正经的印象。

最终的结果就是虹茶和我关系的彻底决裂，对于以前很长一段时间对他的忽视，我一直都感觉到很内疚，很后悔没能好好珍惜和他的回忆，包括一起玩Minecraft时的回忆。

至于玲音，我那时候经常和她分享自己的设定、魔法少女之类的，结果因为我每天总是频繁分享各种信息，我将我的日常全部分享给她，包括和梦暮一起玩什么游戏的日常，经常想找点话题聊，不知为何就被她删列了。

卡布奇诺则是另一种情况，因为我以前都是每天晚上熬夜陪她聊天，后来渐渐地我也感觉很累，不想每天都陪她聊天了，因为时差的缘故熬夜等人实在太辛苦了。

然后因为我每次聊天都聊了太多自己的内容，给了对方我很自我的印象，但其实我和梦暮每天就是这样的方式互动的，梦暮也不会说什么，大概每个人都不一样吧，并不是所有人都习惯我的这种互动方式。

后来我看了界限一书，才终于意识到人际关系是需要有界限的，如果没把握好正确的界限，就会让双方都感觉到身心俱疲，这样的关系无法健康地维持也是自然而然的吧。

正是综上许多因素，她最终也和我绝交了，删我好友，虽然后面加了回来表示孤独摇滚的话题可以经常聊，但她对我控制聊天频率的要求实在无法理解，长期不聊也不行，聊太多自己的事也不行，所以之后就算加回来了也很不自在，生怕说错话，最后还是因为长期不聊又被删了。

事后我无论怎么道歉都没用，对那虹茶还是卡布奇诺都写了很多的道歉信，但都没什么用。当然不可能有用的，其实我心里也清楚，也不应该对本就道不同的人再抱有多少期待了。

卡布奇诺以前推我看的命运石之门我后来也和梦暮看了，直到现在我依然很想很想告诉她我看这部作品的感想啊（哭）。

毕竟这部作品虽然有点残酷，但是讲述的故事深度实在太棒了，主角不断跨越宿命，一次次努力地想要拯救自己的朋友。

而且啊，我其实还有很多很多作品，想和那些朋友一起看，一起分享呢。

* 伸手触碰的遥远星辰
如果在星空下，稍微伸出手的话，也许视角上来看，就能稍稍触碰到那遥远的星辰了吧。

近日，我的体会也正是这样的感觉呢。

最近认识的一个女孩子，一起参加gamejam展会的伙伴，她人很热情，对我很感兴趣，愿意有耐心地倾听我讲述各种东西，和她聊天我十分开心。

后来正式参加gamejam的时候，看见了她本人，虽然相貌相对平庸，但是在我看来她开朗的性格让我有很深切的萌萌感，于是我内心开始有一点点dokidoki的感觉了。

她是一个很热情很开朗，对各种事情都充满好奇的活跃小姐姐。

也是这个时候，我才意识到了，果然我所需要的，其实并不是什么对象，也不是所谓形式主义的恋爱，只是希望找到一个愿意长期陪伴我的小姐姐罢了。如果认识更多有趣的线下朋友的话，或许现实中的我也不会再感到孤独了吧。

她让我看到了，其实遥远的那星辰，伸手就能触碰到。

在展会时我经常跟着她到处乱跑，看着各种有趣的东西，享受着她陪在我身边的这种dokidoki的悸动感，我不能断言这是不是恋爱，但我认为，大概，这不重要吧，重要的只是有她陪在身边，我很开心这样的事情。

这时候的我，也终于开始认同自己了，也正是这次展会时内心的感触，终于让我从心底彻底认同自己作为男性的性别了，我将我心中的这份感触画下来，也就是Chiko(琪可）这个角色形象的设计。

胡思乱想的我，虽然总是有那种心动感，有那种喜欢感，但再怎么喜欢一个人，我也不能轻易地认为自己喜欢她，而是应该认为我和她会成为很好的朋友。因为我也是这时候发现，表白的本质其实是一种约定，而约定只有双方交换才有意义，如果不是双方都喜欢对方的话，那么这个约定没有意义。

所以在我看来，就算真遇到了喜欢的人，我也会更倾向于交朋友，因为对方喜不喜欢自己都是能感觉到的，真正有意义的还是陪伴和创造更多美好的记忆这件事本身，而不是让对方也喜欢你。

不过gamejam总是会结束的，展会结束后，我们在线下做了最后的道别，我告诉她下次见面就请叫我明琪吧，以后就是朋友了，有什么好玩的事情都叫上我哦~，她也表示同意了。

可惜在gamejam结束后，我再去QQ找她分享自己的东西和有趣的视频之类的，她也开始对我冷处理了，不知是太忙了、还是我做错了什么、还是她察觉了我的情绪从而误会了我在追求她。

但不管是什么因素，得不到回应的我最终还是决定不理会这件事情了，继续专注于自己的创作，同时也努力去参与更多的社群交流和沟通，希望将来能有机会认识更多更好的朋友，也希望认识一个能真正发自内心欣赏我，和我志同道合的小姐姐。

* 总结：明琪的恋爱观
再次复盘我的整个心动史，我想到了盗人讲桌中的那枚戒指，那是一枚有着七个人全部记忆和知识的戒指，人总是会透过自己的经历不断学习和成长，但每个人的经历也都有自己的局限性，任何人都可能被自己的局限性所困住，过去的我，大概也被当时的局限性所困住了吧。

也许过去我认识的一些人也一样，会被自己的局限性所困住。

我一直认为，犯错误并不可怕，因为人本身都要在错误和经验中不断学习和成长，包括社会规则，公序良俗、人际交往还有人文关怀之类的，其实都是需要深刻学习和了解才知道的，这也许也和个人所处的环境与人际有关，因为个人的环境和人际对个人的局限性带来的影响很大。

我个人算是比较幸运的，能遇见志同道合的动物朋友社团，他们让我看到了更广阔的世界，我也终于不再被过去的局限性和偏执所束缚，终于能将全部的精力贡献在真正有意义的事情上了。

因为人能从自己的经历成长，我过去的每一段经历，都是我成长的一部分，这些经历不断组合，我也不断反思过去的经历，综合我现在的人际关系，构成了现在的我。

我结合最近的经历，对过去看过的作品和接触过的理论中的恋爱也有了许多新的反思。

其实爱到底是什么，从根本上来讲，这是一个十分深刻的哲学问题，但如何解释这个问题，我想引入《爱的艺术》中的观点，也就是爱的本质是一种能力，无论是爱他人还是爱朋友还是爱自己，对一切事物一视同仁的爱，本质上是一种能力，一种成长和关怀的能力。

因此，要爱他人之前，首先要学会爱自己，这句话实在是说得没错。

其次，虽然爱本身是不限形式的，但我认为任何形式的爱最好都要有，无论是亲情还是友情还是异性之爱，还是更广泛的对世界、地球与全体人们的关怀，都是必不可缺的爱的一部分。

结合近期的经历来看，恋爱，也就是异性之爱的本质其实是一种双向的契约，只有双方交换才有意义。

不过，关于这点，我还想引入森罗博物馆的那样一个片段，在森罗博物馆结局，七濑看着森罗奔向那更广袤的世界。之后同学都调侃森罗也太不负责任了，连电话都不打一下。

但是七濑心中清楚，这个美丽的世界，他是不会离开的。最后就是两人最终又在某处重逢。

又或者可以引入St.Tail的那个表白片段，飞鸟说我不会像别的人那样和你约会哦，芽美表示都没有关系……

由此可见，完美的恋爱，并不需要任何形式主义介入，恰恰被现代社会包装的形式主义，本身就是对感情的异化，他们将感情量化为可被衡量的指标，进行精密计算和推送这类机械化，进而将人也异化成为了他人的附庸品。

虽然我个人认为，友情的最高形式其实是完全超越异性之爱的，但我认为将激素、约定和情感全部融合在一起的异性之爱也是必不可缺的，这些感情都是心灵的稳定剂。
