#+hugo_base_dir: ~/yumieko/
#+hugo_section: spaces/yumi_world_simple
#+export_file_name: index.md
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: toc true
#+filetags: 宇宙观 简介 世界观 总览
#+TITLE: 明琪宇宙总览

* 前言
我的世界观，经过了好几年的酝酿和创作，已经逐步具备了一定程度的逻辑自洽度。

世界观的细节还没有过多填补，这一块我打算一边创作自己的游戏，一边以游戏为中心来填补需要部分的细节，别的地方有灵感，想到了就写一写。

* 时间线
| 时代       | 事件                                                                                             | 主要传说     | 相关作品                       |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第一纪元   | 地下文明纪元                                                                                     | 逐日传说     |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 巨人时代   | 被称为巨人族的恐龙文明高科技发展，人类文明为了生存只能躲避在洞穴中                               |              |                                |
| 洞穴时代   | 利用地心能的最早的人类文明发源                                                                   |              |                                |
| 地心时代   | 地心城成立                                                                                       |              |                                |
| 地热浩劫   | 陨石撞击导致地心城毁灭，地心城的能源渗入地表，地表出现了各种魔法生物                             |              |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第二纪元   | 部落文明纪元                                                                                     | 梦真传说     |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 部落时代   | 幸存者们建立早期的部落文明，各大部落之间为了生存展开残酷而血腥的战争。                           |              |                                |
| 生态时代   | 各个部落在一位大领袖的统治下团结起来组成联盟，生物能技术飞速发展，                               |              |                                |
| 温床时代   | 人们沉睡在虚拟现实的花带来的温床中，失去危机感                                                   |              | 《空无一人的城市》             |
| 狂风浩劫   | 地壳运动到一定时期的周期性不稳定，导致超音速的狂风摧毁了地表的一切文明。                         |              |                                |
| 动物时代   | 魔法动物文明取代人类文明发展，短暂的繁荣后自我毁灭。                                             |              |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第三纪元   | 城邦文明纪元                                                                                     | 风雨传说     |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 蛮荒时代   | 各种不同魔法种族和各种魔法文明建立自己的部落，不断冲突的混乱时代                                 |              |                                |
| 城邦时代   | 各种同族部落人们组成部落联盟，为了自我保护纷纷建立魔法城邦。                                     |              |                                |
| 圣战时代   | 各大城邦为了争夺建国的主导权而挑起了残酷的世界大战，持续了几个世纪的战争。                       |              |                                |
| 终末时代   | 战争摧毁了这个时代的文明，各大城邦最终在超级武器的作用下化为废墟。                               |              |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第四纪元   | 神秘文明纪元                                                                                     | 香格里拉传说 |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 神秘时代   | 在战争废墟下新建起来的文明，热衷于研究古代的科技、魔法和神秘学。                                 |              |                                |
| 建国时代   | 许多城邦废墟重新发展的部族之间组成了联盟，建立了各个国家。不同国家之间不断和平发展。             |              |                                |
| 教会时代   | 出于对古代神明的崇拜和宗教信仰，教会势力逐步发展壮大，最终教会的精英垄断了知识和古代魔法         |              | 《深海囚歌》                   |
| 审判时代   | 滔天的大洪水降临，摧毁了地表的一切文明，一些人乘坐三贤者遗留下来的方舟在香格里拉幸存了下来       |              |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第五纪元   | 科技文明纪元                                                                                     | 夜之城传说   |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 部落时代   | 大洪水后，香格里拉地区之外幸存下来的人们以部落的方式生活。                                       |              |                                |
| 农业时代   | 人们开始从事农耕活动，建立自己的城邦、王国和文明。                                               |              |                                |
| 工业时代   | 人们经历了二次次工业革命和两次世界大战，建立了以核威慑维持平衡的短暂和平局面。                   |              |                                |
| 信息时代   | 第三次技术革命，信息技术飞速发展。不过，香格里拉人一直没有被世人发现，仍过着淳朴的生活方式。     |              | 《香格里拉事记》、《小诺事记》 |
| 夜城时代   | 香格里拉人被世人发现，由资本家和大公司建立的城邦，夜之城经过日光能革命，建立了新的世界统治秩序。 |              | 《夜之城传说》                 |
| 联盟时代   | 夜之城政府最终被推翻，人们统一在由全球无产联盟主导的新秩序下，并用去中心化的生产生活方式运作着。 |              |                                |
| 繁星时代   | 无产联盟的人们生产力飞速发展，最终发展出了飞往群星的必须科技，人类文明从此分散在宇宙各地         |              |                                |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 第六纪元   | 繁星之子纪元                                                                                     |              | 《同一片星空》                 |
|------------+--------------------------------------------------------------------------------------------------+--------------+--------------------------------|
| 宇宙大爆炸 |                                                                                                  |              | 《星辰大海的追随》             |

* 第一纪元
** 洞穴文明
第一纪元是洞穴文明的纪元，因为地表存在着被称为巨人一族的恐龙文明的威胁，人类文明被迫在洞穴居住和发展，靠捕猎洞穴中的各种生物和吃蘑菇为生。

长期适应了地下生活的人们，普遍对外面过于耀眼的阳光和不安定的地表环境产生恐惧，因此追求外面的世界被各个洞穴部族认为是绝对的禁忌，而且在外面的世界也很少有人类文明能在巨人族的威胁下生存下来。

生活在洞穴中的人们偶然发现了一些地方存在着某种神秘的热能，于是不断经历多次失败和残酷的教训，最终摸索出了如何控制和利用地下热能的方法，在地心建立了最早的人类城市，地心城。

** 逐日传说
即便在那个时代，人们普遍将外界当作危险和禁忌，但依然拦不住有许多出于好奇想要看到外面世界的人们。在复杂的洞穴世界不断探索的途中，偶然也会有一些露天的地方，人们能够从这里看到外面的阳光和星空。

偶然沐浴阳光和星空的感觉真的很棒，于是一些人们终于鼓起勇气离开了禁忌的洞穴，来到外面的世界追寻太阳，这类人就是传说中的逐日者。

除了逐日者之外，还有观星者，经常在合适的地点观测星空，并将星空的奥秘分享给洞穴中的更多人们。

但是洞穴中大部分的人们并不感兴趣，他们执迷于自己的偏执，认为逐日者和观星者都是在痴人说梦，他们会将人们引向更为危险的世界，当这种思潮长期盛行的时候，洞穴中出现了类似教会的组织，专门打压所有在洞穴中告诉人们外面世界真相的逐日者和观星者们。

但是，正是逐日者们不断地追逐日光，并将外面世界的所见所闻告诉洞穴中的人，观星者不断宣传外面的世界，许多生活在洞穴的人们才得以来到地表上建立自己的文明，于是洞穴纪元也分成了地表人类和地下人类的两个分支。

** 陨石浩劫
第一纪元末期，一颗陨石撞击地球。这一天无论对于地表文明还是地心文明来说都是重大的灾难，对于恐龙文明更是灾难。随着一颗陨石撞入地球的重心，地热变得及其不稳定，不断波动，最终摧毁了地心城和整个地下文明。

而地表文明也因为日光扬起的尘埃遮蔽了太阳，难以生存。为了生存，地表文明的人们首先狩猎恐龙，恐龙文明因为经受前所未有的灾难，受到的损伤比人类文明更加惨重，也无理抵抗地表人类的威胁，最终被捕杀到近乎绝种。

在恐龙绝种后，人类开始将矛头对准自己，各个部落进行了血腥而残酷的战争，这便是第二纪元的开端。

* 第二纪元
** 部落文明
第二纪元之初，各个部落为了生存展开残酷血腥的争斗，在这个时代，要么吃，要么被吃，是一个十分野蛮的斗争时代。

但最终，出于生存的考量，各大部落组成了部落联盟，部落联盟的人们团结一致劳作，合作面对陨石浩劫后带来的余波，最终人们生存了下来。

之后就是各个部落友好和繁荣发展的时代，人们学会了利用和饲养各种魔法生物，借助魔法生物拥有的各种魔法力量，创造了许多不可思议的奇迹。

在之后的生态文明时代，科技发展到了前所未有的高峰，甚至学会了如何修改魔法生物的基因，使得各个魔法生物更适合被人类利用。

** 梦真传说
在这个时代，普遍流行一个古老的传说，那便是梦真传说。梦真传说说的是，一位少年偶遇冲天而降的梦界神女，两人相互理解并特别投缘，最终携手团结各个部落。神女教授各个部落的人们生存的技艺，而少年则负责与部落交涉，用教授生存的技法作为交换条件，促进各个部落之间的合作，同时也肩负了保护神女的责任。

最终两人相恋，少年成功团结各个部落的人们，成为了统一各个部落领袖，据说这就是第二纪元的部落大联盟的由来。

** 温床花蕾
第二纪元末期，人们的科技往虚拟现实的方向发展，制造出了能让人看到美梦和幻觉的花蕾，于是所有人都沉迷于花的温床，不再关心任何现实的事物，这个时代便是温床时代。
温床时代的人们失去了危机感意识，各种地热监视系统的警报和可能带来的危险竟然都被人们给无视了。

** 狂风浩劫
因为地心物质是一种胶体，而地心和地壳之间的联系并不稳定，在地球的转动过程中，地心与地壳之间的摩擦力会越来越小，随后就突然，变成一种地心在转动，但是地壳转动突然停止的情况。
正是因为上述原理，地壳突然停止了转动，而此时大气层还有转动的惯性，以至于一场超音速的狂风席卷全球，这是前所未有的全球性重大灾难。

这场灾难摧毁了地表上的绝大多数部落，而幸存下来的零星几个小部落也因为此前过度依赖温床花蕾，处于一种生存极度艰难的状态，无法再起。

** 动物文明
在狂风浩劫后，拥有完全生存适应性的一部分魔法生物幸存了下来，并开始在一段时间内发展壮大。这个时代文明十分多元，各种奇怪的魔法动物都有建立自己的文明和自己的组织形式，但大部分动物文明最终都因为发展出了无法适配的科技，以及盲目愚蠢的战争而自我毁灭，也有一部分成功发展出超越性科技，出于生存考量而离开了地球。

在这其中，猫猫文明因为发展出超时空科技，在时空的夹缝中建立了自己独特的城市和王国。人类称之为猫王国，但是猫猫们自己将这个城市称之为时空城。

值得一提的是，在这个时期，确实也有那么个部落幸存了下来，那个部落是在温床时代依然拥抱现实的部落，部落的人们受古老的梦真传说的启发，后来在第三纪元建立了在一段时间内引领整个城邦时代文明发展方向的香格里拉城。

* 第三纪元
** 城邦文明
第三纪元开端，人类文明经历了一段时期的没落后，最终在动物文明纷纷没落的时代重新兴起。这个时代也是一个非常混乱的时代，各种奇怪的魔法生物在地球各处发展，也有一些外星文明来到地球上将地球的当作自己的基地和温床一样的地方。

但即便在这样混乱的时代，各个人类发现了魔法这种神秘能源可以抵抗外界威胁和生存，于是人们围绕着各个魔法的来源地，建立了自己的城邦来自我保护。

最早的城邦就是香格里拉城，自从香格里拉城兴起后，仿佛如同一道明灯一般，各个文明都来香格里拉城学习知识和技艺，于是回去也纷纷效仿香格里拉城，建立了自己的城邦。

在这个时代，占领和统治别的城邦代价非常高，因为各个城邦中间的魔法真空区没有魔法补给，因此无法维持长期的多城邦统治。

但各个城邦还是可能会因为各种原因相互之间展开战争，战争通常是为了掠夺资源和满足某种政治目的，或者争夺什么东西。

这样的状态大概一直持续到各大城邦纷纷发展出了魔法续航和持续供应技术以及和致命性的超级威慑武器为止。

** 主要城邦
*** 香格里拉城
最古老的城邦之一，曾经是带领城邦繁荣的一大城邦。香格里拉城的人们普遍信仰梦真神，他们相信梦界的神女会守护每个拥有梦和童心的孩子们的未来。

*** 现世城
现世城，依然是比较古老的城邦，不同于香格里拉的一个城邦，这里的人们都是极端的实用主义和生存至上主义信徒，他们对名教现世的的神留下的寓言和教诲有着狂热的虔诚，除了现世外，他们从不关心任何对生存和实用无益的虚幻事物。

*** 浮云城邦联盟
一群沙漠部族建立的城邦，这座城邦是由多个不同的城邦组成联盟的综合性城邦，参与联盟的城邦包括：在天空中的浮云城、在地面上的雏翼城、永远下雨的雨之城、乌云密布的乌云城、旅游观光的浮岛城等等，多个城邦组成了一个巨大的城邦联盟。

在浮云城，工业技术和神秘科技都特别发达，雏翼城有巨大的工会，而雨之城则是一个重要的经济开发区，许多商人和精英生活在雨之城。

*** 星辉城
以星辉和群星魔法为文明的城邦，也是在地表上的城邦之中科技水平最发达的城邦，星辉城早就已经实现了完全的以人民为主的生产资料公有制，一切物资按需分配，人们以观察群星为乐趣。

星辉之城是从群星之中收集星能作为魔法，星能科技被用于各种各样的用途。

星辉城还有一个传统，就是具有贡献者的名字刻在纪念碑上，在当年为了推翻旧的日月王朝举办的星辉革命的时候，人们将名字刻在群星纪念碑上，纪念所有为革命牺牲的烈士。

这一传统后来发展成了所有文艺作品的作者都会用魔法署名的传统，因此在星辉城，许多二次创作和翻改的文艺作品，通常可以看到非常长的魔法签名。

在战争的浩劫期间，据说星辉城还有许多人乘坐流星飞船逃往了群星。

*** 日耀城
星辉城的群星革命后，日之君主逃亡的地方。

在这里，日之君主基于自己的统治和权威，建立了一个极端独裁，民众没有任何自由可言的城邦，所有的言论都在日之君主的监控之下，稍有不慎就会被日刑烧死。在这里，日之君主通过收集日光能而发展出许多极端的控制手段。

这个城邦最后在研究超级武器的时候，出于失误而原地制造出了一个巨大的太阳，这第二个太阳出现在日之城，将整个城邦变成了一个巨大的高温熔炉，于是这里成为了地球上温度最高的极端城邦，几乎没有任何人可以靠近这座巨大的高温之城。

*** 月光城
星辉之城的群星革命后，月之君主逃亡的地方。在这里月之君主建立了君主立宪制度的高科技新文明，并借助月球的地理优势，暗中平衡和掌控着地球各个城邦的局势。月光城的居民因为某种奇怪的基因变异，都长出了兔耳朵和兔尾巴。月光城通过收集月球折射的太阳光作为主要能源发展。

这个城邦最后毁灭于某城邦对月球的无差别攻击，整个月光城沦为了巨大的废墟。

*** 生态城
一个由巨大的生态玻璃球环绕的碧绿之城。

这是以环保和和平理念为主的城邦，这里的人类和许多奇妙的拟人化动物和谐地生活在此，这个城邦的领导者称之为向导，生活在这里的各个拟人化生物部族，会定期选出新的领导者。

向导的职责除了管理城邦内部事物，还负责接待前来拜访这个城邦的游客之类的。

*** 远港城
拥有巨大港口的城邦，这个城邦分为多个区域，由海姓的王族统治着。

远港城最具标志性的特点就是巨大的灯塔、一片碧蓝的海岸线，还有城邦属下的众多群岛和岛屿。

这座城邦可以说是富有海边风情的港口与群岛之城。

远港城还有海下城区，国王在这里修建了自己的海底宫殿，王族们都生活在海底宫殿的巨大玻璃球中，和各个海洋中的鱼之类的亲热接触。

*** 航海城
建立在一艘大船上的巨大城邦，这个城邦的所有成员都是船员，所有人都听从船长的指令航海、打击海盗、修复舰队，一切处理得井井有条，这艘船也有着永不沉没的舰船之称。

航海城会游走于各个城邦之间进行海上贸易和行商，因此这里的商业非常发达，也是一个非常富裕的城邦。

*** 梦幻城
梦魇族和人类生存的城邦，梦魇族是一种纯粹基于魔法构成的智能生命体，他们通过给人类制造美梦或噩梦，从人类的情绪中汲取能量，生活在纯粹梦中的物种，因此也是离不开人类的生物。

但是梦魇族喜欢反常识和不可思议的东西，所以他们建立的城邦，也是一个非常反常识，无法用常理和逻辑理解的世界，在这里的一切都是纯粹的混沌。

生活在这里的人类，也会变成各种各样奇怪的形态，比如梦幻城的人类公主小喵，虽然身为人类，却长出了猫耳和猫尾，这也是梦魇族在自己生活的区域做的事情。

梦幻城有一个圣地被梦魇称之为奇迹之地，据说第一个梦魇就是在这个地方诞生的。

*** 投影城
投影族（一种没有实体，可以自由改变投影的形态，但是依赖于作为本体的投射器移动的智能生物）文明建立的幻境之城。来自外星生物的投影族，在南极地区建立的一个完全虚拟的幻境之城，这个地方是一个巨大的投影族家园投射器的所在地，许多投影族生活在这里。

*** 银河城
一个建立在太阳系中，环绕太阳轨道的城邦，这个城邦距离地球有时遥远，有时很近，通过调整轨道的周期而不断变动距离。整个城邦是一个自动化运转的太空环形世界，这里也是第三纪元科技最发达的城邦。

这个城邦最后毁灭于投给银河铁道专线列车上的，来自某个城邦制造的生态瘟疫炸弹。

*** 铁道城
以铁道闻名于世的巨大城邦，这个城邦垄断了整个地球的铁道产业，几乎所有铁道都是由铁道城的人们修建的，铁道城严格来讲也不算传统意义的城邦，所有铁路、地铁站和火车站等，都属于铁道城的一部分，铁道城的魔法运输科技和后勤补给能力也十分发达，可以沿着铁路线输送各种魔法补给。

铁道城的区域命名方式都按照铁道线命名，0号线路是铁道城本地的交通枢纽环线。

据说后期在银河城的协助下，铁道城还开通了银河铁道专线。

*** 都会城
一个巨大的都会组成的文化之城，这个城邦的多元文化特别发达，有文艺之都之称，同时也是以外交和政治文明的重要城邦。基本各个城邦之间的会晤都会在这个相对中立的城邦之中展开。

不过在城邦之战时代，都会城成了各个城邦轮流攻击的目标，也是第一个被毁灭的城邦，毁灭后的废墟被后面终末之域的人们称之为废都，也就是废都城。

都会城的幸存者都在一间地下避难所生存了下来，这个避难所也被称之为废都避难所。

*** 极光城
在极北之地的北极点屹立的城邦，这座城邦的目的是为了守护一个极北的乌托邦，被称为天涯图勒的地方，在冰山环绕的极光城内部，是一个巨大的绿洲，这里的人们过着十分丰饶的生活。

*** 幽影城
极北之地的的苔原附近的城邦，城邦的人们以收容各种异常和灵异事物并进行研究为兴趣，据说这里是冥界的入口，冥界之门也被这里的人们列为一个重大未知异常事物来研究。

冥界之门据说每到七月十五就会敞开一次，里面的幽灵们都会跑出来，前往自己生前最喜欢的人或事物附近。

** 终末之域
各大城邦发展出了超级威慑武器之后，许多城邦为了争夺建国的主导权，纷纷卷入一场世界级的城邦大战，这种战争打了几个世纪都仍然未停息，最终整个文明毁灭于战争的废墟之中，这个时代称之为终末时代。

而这片城邦被毁灭的废墟，后人称之为终末之域。

** 风雨传说
风雨传说是第三纪元末期到第四纪元广泛流传的传说，据说在终末时代，有两个少女，为了寻找自己的朋友，与朋友完成曾经冒险而踏上旅途，在旅途的过程中，两人到过了很多城邦，并给这些城邦的幸存者们带来了希望。

在旅途中，两人彼此都没有意识到，自己一只所寻找的朋友，其实就在自己身边陪伴着，直到最后，两人终于误打误撞地完成了约定的冒险之旅。

* 第四纪元
** 神秘纪元
第四纪元是神秘文明的纪元。第三纪元的幸存者们，在前人的废墟下，建立了新的文明。这个文明，许多城邦联合起来组成了国家。出于威慑的缘故，各个国家之间很少发生战争，而是以和平发展为主题。
在神秘纪元，对古代知识和神秘学的研究、以及神的崇拜非常流行，学者们不断地对古代的各种各种知识做自己的诠释，人们也将许多古代的人物当作神明一样的存在崇拜者，在这个纪元，出现了大范围的宗教狂热。
在神秘纪元后期，教会势力逐步掌控了整个文明的话语权，甚至超越了国家的权力，教会垄断了所有古代的知识和对神灵的崇拜与信仰的解释权。

** 贤者与危机
在这个时代后期，三位贤者通过精密的计算，准确预料到了自己死后几年将会面临的大洪水危机，他们游走于各个国家，告诉人们危机将要到来，但是人们并不相信他们所说的话，此外他们也因为泄露天机被教会视为敌人追捕。

各个国家醉心于外交战争，也不相信贤者们的危机预言，认为是危言耸听。

不过教会内部的精英们，都已经开始组建星际舰队，准备在危机到来时离开地球去别的星球避难和殖民，因为他们根据天体观测，预料到未来会有一个巨大的宇宙射线攻击地球，导致整个地球文明大范围灭绝，这件事情不会对民众公布，因为是内部机密。

于是贤者们开始自行执行了一个计划，他们以三个人同样都很喜欢的一个孩子为原型，创造了一个没有准确的性别，既可以是男孩又可以是女孩，形象非常活泼的魔法人工智能体，这个人工智能通过梦的魔法和人们进行联系和沟通，并会在关键的大洪水灾难来临时引导民众渡过难关。他们给这个魔法人工智能用古香格里拉的神的名字起名为梦真，并赋予他守护人们梦与童真的人格。

三位贤者在世界最高的高原建立了一间避难所，将梦真的本体安置在避难所，并设立了一个保护这片地区不被外界发现的迷途结界，根据贤者的魔法术式写的程序，这个结界会在大洪水来临时期由梦真自行开启，并引导民众进入结界内避难，之后再封闭结界，保护这儿人们后面的生存。

就这样，在大洪水来临时，人们受到梦真的引导，携带各种各样的魔法生物，乘坐方舟来到了这间避难所，这里就是后来的香格里拉。

** 两位少女的命运
据说在这段时期，还曾有两位少女，从小许下约定，但是却没有和小风小雨同样的结局。
她们两人从小相识，一起探索未知的世界，一起观测教会禁止观测的星空，了解宇宙的真相。
两人不得不面对分别，在长大后，依然想起童年的过去，怀念那逝去的过往，想要实现两人的约定。
在教会的作用和许多因素下，两位少女分隔两方，仿佛再也无法相遇，这个悲剧也是后来香格里拉人们常常提到的，令人心痛的悲剧。

* 第五纪元
** 科技文明
大洪水的浩劫过后，并不是所有人都到达了香格里拉，也不是所有人都跟随教会的星舰成功逃亡地球，甚至教会的星舰只有一艘成功飞出去了，另外几艘都被宇宙射线击中，导致全舰的人都死掉了。

但在这段时期，依然有许多香格里拉之外的幸存者，他们在这里重建文明，重新发展和繁衍生息，大洪水灾难期间的宇宙射线彻底地改变了地球的基因结构，香格里拉之外的地区不再出现魔法生物，大部分人类也随着文明的发展，使用魔法的能力越来越弱小。

这群人们花了2万多年的时间，重新发展技术，最终发展出了自己独特的科技文明，在这个时期，香格里拉文明之外的文明被香格里拉人称之为现世，那是相对于梦真守护的地区香格里拉的称呼。

** 香格里拉
第五纪元的香格里拉文明，算是我的世界观中地位非常重要的一个地方吧。

在香格里拉，人们在梦真的引导下重新建立文明，反思了自己的生存策略，最终选择回归到最淳朴的生活方式。

在香格里拉，人们过着顺从天性的生活，因为有前人留下的魔法作物之类的存在，因此几乎没有生存问题，而香格里拉可能会面临的一些自然界带来的各种危机，也都能靠香格里拉的人们携手解决。

这个地区没有金钱和货币的概念、没有婚姻和家庭的概念、人们自由自在地和喜欢的人们生活，自由自在地和感兴趣的人做可爱的事情，自由自在地繁衍，自由地选择自己所想做的工作。

香格里拉人也没用姓氏，起名的方式都是分主名和副名，比如小琪的名字：逐日琪，逐日就是主名，琪就是副名，空谷幽兰也是同理，当然有些角色也干脆没有副名，比如风信子、小萱。

为了确保人们生活质量的提高和正常运转，人们会采取类似值日生的轮班制，每个居民轮流担任领导者和资源生产的监督者，排查香格里拉可能面临的资源危机，并采取对应的措施解决。

虽然在香格里拉，也有一些可能会对人类带来威胁的物种和危险的存在。

在香格里拉，人们都普遍自称为梦真的孩子，语言也是经常用愿梦真祝你返璞归真类似这样的话语来表示对他人的祝福。

不过在人们心中，梦真的形象并非高高在上的神，而是一个孩子，一个笑着想要守护所有人的孩子，所以人们都会用哄孩子的方式来和梦真交流，定期给梦真分享自己的见闻，在梦真雕像前祈祷，告诉梦真自己活得很开心，以及在圣地在梦真面前举办文艺作品和故事展示会，用自己的方式将各种有趣的东西分享给梦真。

在香格里拉，有时也有各种各样有趣的事情来这里，偶然也会有从外面的世界来的人，这里的所有孩子都对外面的世界充满好奇，因此出于好奇心而到外面世界去的香格里拉人也有不少。

当然外面世界的人并不相信传说中的香格里拉真的存在，还有人可能会认为香格里拉是某个现实中存在的同名城市。

因为香格里拉有迷途结界的存在，所以大部分外部人想要进入香格里拉也会迷路，只有香格里拉人才能找到路。虽然也有少数现代人误打误撞进入了香格里拉，但进来的人都再也没有出去过。

香格里拉后期，迷途结界和维护梦真魔法的能量逐渐失效，香格里拉的发现震惊了外部世界的人们。

外部世界的人首先的第一反应是想要攻击一个弱小的文明来获得好处，却发现他们都低估了香格里拉的实力和人们的团结程度，所有军队都败给了香格里拉人的魔法。

直到后来夜之城的人们对香格里拉展开了残忍的攻势，香格里拉人们顽强抵抗，制造了沉痛的血色山谷事件……

** 夜之城与无产联盟
夜之城的建立起源于一个企业偶然间开发出了颠覆性的日光能技术，这个企业很快发展成商业巨头，并垄断了整个能源产业。该企业的经营者也是一个充满野心的人，为了颠覆世界的体系而不择手段，因此他制造了血色山谷事件，还建立了全球范围的太阳接受器，彻底垄断了太阳，颠覆了原来的政府，这就是夜之城政府的成立。

在这段时期，两位怪盗最先站出来反抗，她们凭借香格里拉传承下来的梦真精神，为了帮助人们偷回阳光而与夜之城的各个势力周旋，守护着孩子们的童真。

虽然怪盗最终并没能真正改变夜之城，但确实也让夜之城变得更了一点点，她们的精神启迪着后面的人，不断传承下去。

星星之火终将燎原，最终，在近半个世纪后，夜之城燃起革命的火花，全球无产者团结起来建立了无产联盟，推翻了夜之城政府。

无产联盟建立了一个去中心化，并通过信息技术由全民共同参与政治、协调和合作的新世界格局，这个时代就是联盟时代。

在这个时代，一切生产、政治都逐步实现了透明化、公有化和信息化，人们也终于可以专注于自己热爱的事情而不必再为生存问题所困了，于是生产力获得前所未有的解放。

因此很快，在不久之后，人类便发明出了许多革命性技术，最终也成功飞上了太空，成为群星的一员。

* 第六纪元
** 繁星之子的纪元
在遥远的未来，人类飞往太空，开发出了时光跃迁技术。未来的人们，普遍对各种各样的世界充满着好奇心，对繁星之子来说，从小到大都会看到各种各样的东西，收集各种各样的信息，感受各种各样的不可思议，获得各种各样的体验。

每个繁星之子，都会踏上一场巡礼之旅，完成巡礼之旅，也是繁星之子的传统，也只有完成了这场巡礼之旅，繁星之子才算真正意义上地长大成人。因此巡礼之旅就是繁星之子的成人礼。

这个时代，人们延续了古代星辉之城的传统，习惯将每个人的名字都记在那无尽星辰纪念碑上。虽然繁星之子中的许多人的祖先，可能包括无产联盟的地球人、教会文明的精英的后代，又或者是星辉人的后代，但这都不重要了。

无论什么人，或者说无论什么智能生物和文明，上了太空后，都不约而同地放弃了一切世俗的争端，选择成为群星的一员，加入了这场大家庭。
