#+hugo_base_dir: ~/yumieko/
#+hugo_section: fictions/the-same-galaxy
#+export_file_name: index.md
#+hugo_auto_set_lastmod: t
#+HUGO_PUBLISHDATE: 2025-06-21T06:41:00+08:00
#+hugo_custom_front_matter: toc true
#+filetags: 第六纪元 繁星时代 星空 友情
#+TITLE: 同一片星空

* 序
一颗流星划过天际……

繁星的孩子哟，你们执意踏上旅途，既然去意已决，我也无意阻拦，那是一趟漫长而遥远的旅途。

你们乘坐着流星飞船，只管去吧，两位孩子，去看看这宇宙的奥妙。

繁星之子中，名叫天音的姐姐朝空音挥了挥手，“走吧，完成我们约定的巡礼之旅吧。”

繁星之子的妹妹星音微笑着，与天音一同乘上了流星飞船。

就这样，两位繁星之子，天音和星音，手牵着手，乘坐着流星飞船，划过天际。

* 逐日的星空
数不清是多少亿年前了，以地球的历法来算，大概是被称为人类文明第一纪元的侏罗纪吧，这个时代是逐日传说的时代，也是恐龙文明兴起的时代。这时大部分的人类还居住在洞穴里，躲避着恐龙的威胁。

但是，一位逐日者因为看见了太阳，力排众议离开了洞穴，踏上了追逐太阳的旅途，这个人被后来的人称之为逐日者。一次偶然间，逐日者遇见了对自己来说最好的挚友，那是另一个洞穴里逃出来的观星者，因为同甘共苦，于是一同踏上旅途。

白天他们追逐太阳，夜晚则一同在星空下休息。

逐日者与观星者今天也在追逐太阳，两人躺在星空的下的草地上休息，望着那片星空。

“为什么，你要如此执着地追着太阳跑呢？在宁静的夜晚，停下来看看星空，又有何不好？”，观星者跟随逐日者的旅行许久，始终无法理解逐日者，于是发出了这样的疑问。

“是啊……为什么呢？星空确实也非常美丽，那是一种神秘而灿烂的美。但是太阳的话……”，逐日者停顿了。

“也许……这就是我的命运吧”，逐日者说道，“因为看到了美丽而光明的东西，想要让所有人都看到，让所有人都感受到，所以才会追寻着太阳落下的地方。”

“原来如此”，观星者闭上双眼，眼前仿佛浮现出那名逐日的少年，不断向着光明奔跑的画面，“我理解了，虽然星空的美丽是永恒的，但只有太阳可以照亮整个地下世界啊……”

观星者的眼前，仿佛看到了那轮红彤彤的太阳，沐浴永远光明的阳光下，仿佛心中一切杂念都消去了，一片平静。

“也许太阳，是所有星星之中，最耀眼的那颗吧……正是为了寻找这颗星星，我才会与你一同踏上旅途啊”，观星者这样说道。

“这篇星空，是永远美丽的星空呢……但我希望，总有一天，所有的人们，不必再躲藏在那阴暗的洞穴里，而是一同欣赏这片壮丽的星空啊……”，逐日者这么说到，不知不觉牵起了观星者的手。

一颗流星划过天际，两个人，就在这样美丽的星空之下逐渐迎来了又一个黎明。

* 梦真的星空
第二纪元末期，那是地表一切文明痕迹被狂风摧毁后的时期，各个人类的部落之间为了生存，展开了激烈甚至嗜血的征战。而在这样的时代，一个美少年，那是位自幼在斗争中失去双亲，作为孤儿抛弃，偶然间又被敌对部落的亲人收养，长大后养父母又被原来的部落消灭而无依无靠的少年。

这个少年，深知人类无休止的争斗只会带来更惨痛的结果，于是游走各个部落之间想要停止战争，但都被部落视为敌人攻击。被各个部落排挤，无法被理解的他，偶然间遇到了从天而降的女神，据说那是自梦界而来的少女，虽然不知道她叫什么，但是后人都称她为梦真，即梦与童真的神明。

两人都是平日被排挤的异类，于是很快相识，两人都能相互理解彼此的理想，一同踏上了阻止部落之间斗争的旅途。

少女给各个部落传授知识和技艺，安抚人们的心灵，而少年则在各个部落之间交涉，平衡部落人们的利益。

今天少女与那位少年依然在旅行途中，两人坐在草地上一同看着星空。

“你的故乡，会在哪颗星星上呢？”，少年指着一颗星星问少女。

“不知道呢，也许我并没有故乡吧，又或许群星皆为我的故乡……”，少女回答，“我们住在天上的人，总会在群星之间游荡，没有固定的住所呢。”

“这样，不就像我们一样了吗……”，少年说道，“总是在各个部落之间游荡，都是居无定所，无家可归之人。”

不知为何，少女看着少年，微笑了。

“你笑什么？”，少年看着少女的微笑表示不解。

“没什么……就是觉得欣慰呢。在茫茫星空之中经历无数孤独旅途的我，如今终于找到了自己的归宿呢。我喜欢这片大地，喜欢这颗星球，所以，能永远留在这里，总觉得有点开心~”，少女说道。

“我们一族虽然自由地翱翔于星空之间，但孤独也是无法摆脱的宿命，特别是我这种希望能交到很多朋友的人……”，说道这里，少女顿了顿。

“那些星星们，总是孤独而孤傲着的呢，各自拥有各自的想法，不愿意和我交朋友，所以，来到这里，遇到你，我觉得很幸运，因为我终于交到朋友了呢~”，少女望着少女的脸颊，嘻嘻地笑着。

“嘿嘿~不仅如此，而且我和各个部落里的那些人，相处得很好哦，虽然战争什么的确实很讨厌……但是，我理解他们只是饿了，当他们不用战斗也不用感到饥饿的时候，斗争便自然会停止，他们也能表现得非常友善呢……以后也许还会遇到许许多多的朋友，想到这里，我就觉得自己十分幸福呢……”，少女继续说道。

“诶嘿，这一切，都要感谢你……”，话音刚落，少年便一把抱住了少女。

“我才是……要感谢你。如果没有你的话，我什么都做不到，只能眼睁睁地看着那些愚蠢的家伙自相残杀，不是你死就是我活……我厌倦了这种战争，所以才想要让各个部落成为朋友。如果没有你教授给部落人们获取食物的方法的话，也许斗争永远也不会停止吧……所以说，我才要感谢你，没有你，我什么都做不到……”，少年紧紧地抱住了少女，两颗泪水从脸颊滑落。

“诶嘿，但是没有你保护我的话，也许我早就被他们杀死了吧。所以，只要有你在，我便什么也不用怕了，能够很幸福地在这片土地上生活哦~”，少女也流下了欣慰的泪水。

一颗流星划过天际，两人就在这样的星空下，相恋了。

* 约定的星空
第三纪元末期和第四纪元末期，都曾有两位少女，许下过约定。

第三纪元的那两位，小风和小雨许下的是去世界各地旅行的约定。

而第四纪元的两位少女，许下的则是在星空下再会的约定。

** 第三纪元 终末时代
在第三纪元，各大城邦相互之间爆发激烈的战争，每个城邦都想要建立统一天下的帝国，谁也不让谁，城邦之间的战争逐步白热化，各个城邦相互使用超级武器，导致整个世界被摧毁轰炸，生灵涂炭。

在世界毁灭后的时代被称之为终末时代，而终末之域便是这片战争损毁最严重的土地。

“那么，约好了哦~总有一天，我们要旅行到各个地方去看看”，在星空下的秘密基地，小风和小雨看着远方的各个城邦的景象，许下了这个约定。

不幸的是，在那之后，两人跟随各自的家庭而分别，再会时便已是终末战争打响的大审判日。

那一天，两人偷偷从家里跑出来，回到了早已被毁灭的秘密基地，望着那片星空，随着那毁灭一切的彗星风暴一同化为灰烬，永久地沉眠于星空之下。

在那之后，不知发生了什么，两人在末日后的终末世界醒来了，失去了曾经的记忆，相依为命的两人，在各个城邦之间旅行，寻找着自我。

今天小风和小雨，依然也在寻找着自我。

小风和小雨坐在星辉之城的群星纪念碑旁，看着由星辉之镜从宇宙中映射过来的那片星空。在这末世，时间仿佛失去了意义，两人就坐在这样的地方看着星空。

“这块奇怪的大石板上，为什么会有这么多密密麻麻的奇怪符号呢？”，小风问道。

“不知道诶，不过，一定是人们为了纪念什么，而刻在这块纪念碑上的碑文吧。”，小雨回答说。

“呜诶，纪念魔法少女吗？”，话音刚落，小风就被小雨敲了敲头，“呜诶诶，怎么这样……小雨又欺负人家啦……”

“也许是为了纪念一些做出过贡献的人吧”，小雨这么说道，仔细看了看碑文，然后低头叹了口气，“不过……看不懂呢……”

“不过，这上面写的名字，多到数不清呢”，小雨感到疑惑，“对这个城邦的人来说，值得纪念的人，真的有那么多吗？”

“呜诶，就像天上的星星一样多诶？”，小风说。

“是啊，就像天上的星星一样多呢”，小雨从背后抱住了小风，小风则是往后靠，小雨就这样抱着小风，揉着小风的脸蛋，躺在了星空下。

“我想，这里的人，一定很喜欢星星，所以值得纪念的人的名字，也会像天上的星星一样多吧……”，小雨说出了自己的想法。

一颗流星划过天际，两位少女就这样在星辉之城的星空之下舒服地睡着了。

** 第四纪元 大洪水前夕
在第四纪元大洪水之前的时代，是教会和各个国家崛起的时期。

人们好不容易在终末之域的废墟和以及上建立起新的文明，随后便是教会专制知识的时期，世界诸国服从各大宗教的权威，彼此间也不断斗争，每个国家都希望为自己的国家争夺一份筹码，因而陷入外交斗争、军事威慑和冷战之中。

在这样的时代，除了教会的精英们，谁也没有意识到大洪水即将来临。为了避免混乱，教会封锁了大洪水的信息，并大力封杀一切宣称灾难即将来临的学者，暗中组建了带领各个教会精英们踏上远征的舰队，准备在大洪水来临时先一步离开地球。

这个时代，三贤者也在为灾难做准备，他们不断与教会周旋，希望能让各国意识到大洪水的危害，团结起来对付危机。但是各国忙于战争，于是贤者们只得自己暗中建造方舟，还以最喜欢的一位孩子为原型创造了魔法人工智能梦真，以帮助人们应对大洪水的危机。

就在这段时期，有两位少女，虽然一位是贫穷家庭的孩子，另一位是精英的孩子，但两人外出游玩时偶遇，之后一同冒险，一同在那星空下探索秘密。

她们一同看见了教会建造的巨大飞行舰队，认为那一定是鲸鱼，用童趣的眼光好奇地看着这个世界。

分别时，两人在这星空下，许下了再会的约定。
“约好了哦~，等我们长大后，无论过去多久，一定还要来这里继续探寻星星的秘密哦~”

“嗯，一定会的，希望总有一天我们会再会……”

两位少女是这样说着，其实两个人那天，都在故作坚强，强忍着的泪水，在分别之后决堤。

许多年过去了，两位少女并没有像她们所想的那样迎来再会，而是分隔天涯海角。

精英的那位少女成为了学者，找到了宇宙的真相和最新的理论，却被当作异教徒打压。

而贫穷的那位，家里为了生活忙碌而不断奔波，却依然仰望星空，控诉那些大人们实在太过无聊。

就在大洪水前夕的那天，教会的飞船也即将从宇宙中启航。

贫穷家的那位少女，站在那约定的地点，一片蓝的地面上，仰望着上方习以为常的飞船以及星空景观。

而另一位少女，站在那飞船的顶端，准备从天空中一跃而下，以实现两个人再会的约定……

在这天前夜，两个人仰望着同一片星空，做着最后的致辞。

站在地面上的少女自言自语着，“你啊，其实是个爱哭鬼呢，却总是在故作坚强……现在我又来到了这个地方哦。”

“彼方的那个你，还好吗？我好想像天空中的彗星一样，立刻飞到你的身边呢……”

“那些大人什么的，天天只想着钱，看不到美丽的星空，真是太无聊了，太可悲了……最讨厌了……”

“我说你啊……和我一起去冒险好吗？把那些大人们全都忘掉吧，难道真要像他们一样成为无聊的机器吗……？”

仿佛心有灵犀一般，站在飞船上的少女说道，“你啊……好像真是个爱哭鬼呢，总是在故作坚强……”

“多想再和你一起冒险啊，我想探寻那星空的奥秘，我好想给你展示那星空的真相……”

“虽然我早已因为研究禁忌的学术，被教会废除了学者的名号，但我想，你应该会相信我所解释的那个宇宙真相的吧……”

“在这个世界上，也许最懂我的人，还是你啊……”

站在地面上的少女说，“要是放弃就好了……所有人都是这么对我说的，但是……”

她用魔法相机，显示出了几张照片。

“呜呜呜……这些照片，一直都是当年拍的哦，彼方的那个你啊……我想你一定还记得我吧……要是能到约定的地点，就好了……”

站在飞船上的少女说道，“一旦离开了这个地球，就再也无法见到你了呢……想想就寂寞，要是跳下去就好了，结束一切，我想永远在这片土地上和你在一起……好想再会……”

一道流星划过天际，两位少女，即使分隔彼方，但依然一同望着这片星空，异口同声地说，“来吧……，在这片星空下，迎接我们的再会吧！”

* 香格里拉的星空
大洪水的浩劫后，留在地球上的人类幸存者氛围两批，一批躲在了世界最高原的避难所，建立了香格里拉文明。另一批则迁徙到世界各地，建立了科技文明。

许多年后，在香格里拉，这一代的香格里拉向导风信子在忘忧草的平原中偶然遇见了突然出现在香格里拉的神秘少女，小萱。从见面的那一刻起，风信子便喜欢上了小萱，她总是担心这孩子的安危，于是总是追着活泼的小萱到处乱跑。小萱虽然如同小动物一般，并不擅长说人类的语言，但是对香格里拉各个地方都充满着好奇，总是在各个地方到处乱跑，风信子为了追小萱，也跟着小萱在各地旅行。

今天风信子也在香格里拉的平原上追逐着小萱。

“等等我啦，小萱”，一如既往地呼喊声，风信子气喘吁吁地在星空下奔跑着。

“哼哼哼哼嘿嘿嘿嘿”，小萱只是笑着，在这片星空下跑来跑去。

不过追逐终会疲劳，“呼……”，小萱终于累得跑不动了，于是风信子看准时机扑过去。

“抓到你了~小萱~”，风信子得意洋洋地笑着，仿佛不会放跑眼前的猎物一般，紧紧地抱着小萱不放手。

“哼哼哼哼嘿嘿嘿嘿~”，小萱像是小动物一样发出哼哼嘿嘿的声音。

“不行……你这孩子，还是像往常一样可爱呢~”，风信子笑着抱着小萱，两人尽情地缠绵在了一起，做着可爱的事情。

“不过话说回来，真的感谢小萱你哦~如果没有小萱的话，我也不会看到这么多不可思议的事物了呢”，风信子说道，“即便是在这片一如既往的花海，夜晚来观赏星空，也会有不一样的感受呢~”

“嘿嘿嘿~”，小萱得意的笑着，发出可爱的声音。

此时，星空的光亮增强，在星空的照耀下，随着萤火虫的舞动，周围的风信子花，竟然发出了五颜六色的光芒。

“真的好厉害耶，在星空的照耀下，这里的风信子花，也会发出前所未有的色彩呢。”，风信子对小萱笑着，“最喜欢你了哦~小萱……”

“你知道为什么我喜欢风信子花吗？小萱”，风信子开始自言自语说。

“因为，在香格里拉，在梦真那孩子的守护与注视下，这里的生活，就如同风信子一般丰富多彩呢……”风信子说道，“也许，风信子这种花，正是代表了我对香格里拉之爱的花吧……”

“呜呼呼……”，小萱似乎感觉到了疲劳，开始自顾自地在这片星空下睡着了。

“真是的，这孩子……在这种地方睡着，会着凉的啦~”，风信子对小萱露出了姨母般的微笑，“不过，真拿你没办法呢……”

一道流星划过天际，风信子拿出事先准备好的被子，就在这片星空下的花海之中，和小萱一起盖上被子睡着了。

* 
