#+hugo_base_dir: ~/yumieko/
#+hugo_section: reflections/drjz
#+export_file_name: index.md
#+hugo_auto_set_lastmod: t
#+HUGO_PUBLISHDATE: 2025-06-21T06:41:00+08:00
#+hugo_custom_front_matter: toc true
#+filetags: 作品感想 盗人讲座 游戏感想
#+TITLE: 盗人讲座感想总结
* 前言
这些是我游玩《盗人讲座》时的心得感想，我在这里做个汇总和记录，分享给大家。
《盗人讲座》是一部很老，虽然体量很小，质量相对粗糙，但是讲述了一个非常有趣的故事的作品。
这个作品的核心，虽然表面上是讲盗贼的故事，但是个人认为也是在讲述关于人故事，里面许多桥段，都讲述了作为自由的人和社会的底层应该用什么样的态度面对强权等势力，保持自己的独立性和与剥夺自由的势力抗争的精神。
既然自己的东西被偷走了，那就偷回来，这句话是这部作品的核心精髓。
这部作品，塑造了一个自由，不受约束的盗人小镇，在这个小镇上唯一的法律只有不能杀人以及不能贩卖毒品。
小镇上的所有人都是不愿受帝国的压迫和约束，虽然出于各自的生存目的，但都有追寻自由生活方式的人们，他们都是独立而自由的人，懂得守护自己的生活和专注于自己热爱的事物，有着某种返璞归真的能力。
一旦遇到这样的生活要被打破的灾难，他们最终都会团结起来，一同对付帝国的入侵者。


* 第一课
《盗人讲座》开场剧情是一位从小就梦想自由，想要去外面自由世界的王子，在被帝国军颠覆了国家并追杀的情况下，终于能借机会实现成为盗贼的梦想了，于是王子来到了盗贼之都的工会，为成为盗贼而听取讲座。

盗贼并不一定都是坏人，各种各样的盗贼，虽然坏的也有，但盗贼也是从强者手中偷东西帮助弱者的英雄。

讲座的第一课就是偷盗，讲师讲解了这里的规矩和身为盗贼的原则，比如不能闯空门、禁止偷受保护的工会等组织、偷东西被发现要将免罪符交给对方。

游戏的情境塑造非常有趣，比如一位热爱书籍的老爷爷，你可以卖书给他，他会热情地给你讲解书中的故事并说出自己的看法，有热衷于收集各种色情物品的色情狂。

盗贼也有各种各样，比如有想要偷女孩子心的爱情小偷，有会鼓励新手勇敢偷盗的大姐姐，（估计这位大姐姐也是故意让你偷她的）。

游戏里面有个贩毒商人相关剧情，其中有位情报商调查商人的事件，和主角相遇后，也一起打破了商人的贩毒交易。这个情报商有一枚继承了各种各样的人记忆的戒指，她受到戒指中人执念的影响和引导才决定要破坏商人的交易。

最后打败了商人后，她因为受到戒指中某位痛恨恶人的刑警的执念驱使，执意要杀死商人，但是被主角拦了下来。
她受到戒指的观念影响，觉得坏人无论如何都会作恶，不可能改过自新。
但是主角提醒了她受到戒指的记忆而迷失了自我。她想起来，自己真正的看法也是并不希望杀死商人，而是交给工会处理，并感谢主角。

* 第二课
第二课的重点是学会观察。
要以古代遗迹或大富豪的宝物为盗窃目标的话，绝对要注意的，就是眼睛看不到的空间的存在。

在第二课的观察考试（其实是寻找老师的捉迷藏考试）期间，之前那个叫卡尔莉的盗贼找主角办事，要偷走工会成员的日记，于是我把盗贼工会的成员都偷了一遍。

同桌身上有各种女孩子的情报，让人dokidoki的各个街道上的女孩子的情报。

高价值的宝物里面住着恶魔，据说宝物也会让人的心变成恶魔。

一位翼人，曾经是大盗贼比尔的盗贼团成员，但他因为作为翼人永恒的生命，无法面对正常面对一次次失去的熟悉的人，面对这样的寿命带来宿命，她自愿守护在墓地，只有在曾经的盗贼团才有能接纳她的容身之所，自己因为背上有双翼而无法被人类理解和接纳。

之后在工会的密道深处，我还偷到了比尔的宝刀。

我试图偷工会长，但工会长直接明白了我的意图，告诉我没用的，常年作为盗贼相关的工作，以他为目标早就会被发现，于是主角表示自己是修行不足。

引导主角来到盗人之街的精神导师是义贼库雷塔，而在主角找到老师之后，正好出现了一个义贼库雷塔所保护的抵抗组织成员正在被追杀的事件。

主角身为王城被攻占，逃亡和被悬赏中的王子，作为新手盗贼在盗人之街修炼，是一个十分了不得的神奇状况。

* 第三课与第四课
第三课讲到了一个重要技能，误诱导。在课后询问了之前从帝国爪牙下救来的女子，得知了战场上的真相，透过各个人的日志，我们发现希顿老师早就知道这些讲桌的学生们背后的底细。
第三课的御饭团粉碎也是很有趣，一群少女抢着要粉碎主角的超级大御饭团。

而在第四堂课，准备前往最近的村落实践时，讲座被打断，帝国的赏金猎人带走了女子和小孩，并告知帝国将要接管街道的消息。
盗贼之街开启紧急会议，主角看不下去会议希望明哲保身的决定，于是冲进去提出了自己的看法，告诉了大家自己的过去和经历。
这时候大家全都纷纷站出来请命，要完成史上最大的盗窃计划，偷走帝国的首都。原来这条街上的人们，都不希望这条街被帝国夺走，要尽全力守护这条街，每个人都付出了自己的行动。

最终的计谋也让人感觉非常有趣，用生动击西技术蜂拥而入城内，反复诱导城内的士兵乱跑，将城内的士兵耍得团团转。趁着士兵谈话将门堵住，最后还有王子当诱饵亲自上城堡内将敌人引开。

* 盗贼与恶魔的故事
这是在盗人讲座游戏中途看到的一个故事。
曾经有个盗贼，因为一次失误，放出了上位恶魔古雷达戴蒙德，为了一生只有一次的失误，恶魔让一个少女失去了意识，盗贼也以此不断责备自己。
盗贼为了唤醒这个少女，来到了盗贼之街，拜托友人照顾这个少女，他一次次四处寻找魔法之药，尝试失败后又开始寻找，街道上的人听见传闻纷纷行动起来。
最终少女被魔法师的魔法之药所救，而古雷达戴蒙德出现在众人面前，但在人们的协力下，恶魔最终被盗贼与众人协力彻底消灭。
这个故事非常令人感动。

* 氛围与角色
这部作品的小镇情境和角色塑造非常棒，小镇上每个角色都有鲜明的个性。
比如，收藏书籍的爱好者，会给你讲各种各样书籍的故事，并说出自己的看法。
虫虫俱乐部，会定期举办奇怪的虫虫舞会，并将看到虫虫俱乐部秘密的人都拉入伍（实际上就是秘密基地）。
同桌，想要学习如何偷走女孩子心的爱情小偷，经常搜集各个少女的信息，每天都在悄悄地对某个女孩子告白。
吉诺大姐姐，会热忱地鼓励你鼓起勇气迈出第一步前进。
野心勃勃的同学，一起偷各个成员的日记阅读，虽然总是想着要变强，但其实也有体贴人的一面。
工会长，慈祥的中年大叔，用温柔而的眼神看着年轻人的成长，并为之感到高兴。
各个狂热收藏者，热忱于自己热衷收藏的事物。
魔法亭的老婆婆，对小孩子非常慈祥。

这条街道，現在來看，大概就是不被帝國的階級意識和對立意識而生的侵略慾所控制。而仍懂得樂在其中、感受生活的人們的聚集之處。

* 结局
希顿老师曾经的朋友，为了各自的志向而分道扬镳，他们给出的话都是，盗贼究竟是为何而活，但最终各自都找到了自己的意义。
但他现在理解了，身为盗贼，为了守住自己的骄傲，既然东西被偷了，那就要偷回来，为了偷回自己重要的东西而战斗。
希顿老师将自己隐藏的惊人战技倾泻而出，以盗贼之身份直接反杀了著名的杀手赏金猎人。

主角最后遇到了著名的赏金猎人使犬人，王子将使犬人引到下风处，利用狗会追击猎物不放的特性，以及让另一个盗贼借助麻痹粉的威力，让使犬人中了麻痹之毒。
这就是主角所学到的知识，误诱导。让敌人误认为目前的重点是追击眼前的目标，而迷失了对其它目标的注意和判断。

无论哪个时代，顺从自由而活，并反抗命运，将被偷走的东西偷回来，这就是盗贼的天性，王子从盗贼的课程中学到了这一点，下定决心要继续与帝国战斗，将国家偷回来。

这也正是对面对“宿命”之勇气的鼓励和赞歌，主角盗人之街受到盗贼课程的启发，最终决心要面对现实，守护对自己来说重要的东西。

主角沒有外掛 唯一的外掛是那個戒指(而且也只是知識而已) 但如果沒有返璞歸真的心是會被偏執支配的。

＂宿命＂具體說的話，因為遭遇的事而生的陰影和慣性思維。

* 恶魔的与天使的故事
这是在游戏中搜集线索，努力触发真结局过程中整理出来的故事。
恶魔与天使，曾经是两个种族，一场大战毁灭了所有天使的男性，虽然最终也将恶魔封印在地上世界。
而天使，因为失去了所有的男性，女性有了一个共同的誓言，来到下界伪装成人类，为人类传递文明和知识，将人类当作孩子守护。
曾经，天使们也和人类一同与恶魔战斗，人类利用恶魔的弱点最终封印和战胜了恶魔。
M系列即为永远的器物，是翼人为了帮助人类制造的器物。
那些永远的器物，不死不老，永远帮助人类的器物，正是拥有几乎永恒生命的天使一族所做。
无论是那个能唤起曾经回忆的魔法音乐盒，还是魔法之剑，又或是酷似天空之城人偶的魔法石人偶，都有着自己的使命，也不断接续着自己的使命。
曾经盗贼团的天使，如今逃避一切自己的宿命，沉眠于安息之地。而从魔王那偷来的会说话的魔剑，曾经也是一件器物，但是被在魔王的使用下迷失了自我。
但最终，魔剑在听到那音乐盒的声音后，终于重新想起了自己的意识与自己的使命，这个剑还会给小孩子讲故事XD。
在他看来，比起待在昏暗的地下室什么都不做，还不如帮助人类一同战斗。

而那个天使，枫铃，因为永生的宿命，一次次看到身边熟悉的人类死去的悲伤，决心将自己封印在墓地中，逃避着一切，但最终也因为看到魔剑无论怎样，也要帮助人类战斗到底的态度，以及街道面临着危机无法坐视不管，决定出来协力拯救那个少女。

这既是一个悲伤的故事，又是一个令人钦佩和感动的故事。

* 最终感想
这是关于永生宿命和如何破除宿命的真相的故事，盗贼哪怕偷东西最初只是为了填饱肚子，但是身为盗贼，也会为了守住自己的骄傲而战。
主角知道正面战斗并不是盗贼的做法，所以一直没用魔剑与敌人正面抗衡，而是用偷的方式战斗，借助误诱导对付敌人。
